### ISSUE TITLE
lfe package is failing to build

### ISSUE THREAD

**Issue by akbertram** [bedatadriven/renjin-release#7]
The `cran:lfe:compileNamespace` task is failing due to a runtime exception in startup.R. Here is the log:

```
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Evaluating '/home/runner/work/renjin-release/renjin-release/packages/cran/lfe/R/bccorr.R'
Evaluating '/home/runner/work/renjin-release/renjin-release/packages/cran/lfe/R/btrap.R'
Evaluating '/home/runner/work/renjin-release/renjin-release/packages/cran/lfe/R/cgsolve.R'
Evaluating '/home/runner/work/renjin-release/renjin-release/packages/cran/lfe/R/chmethod.R'
Evaluating '/home/runner/work/renjin-release/renjin-release/packages/cran/lfe/R/compfactor.R'
Evaluating '/home/runner/work/renjin-release/renjin-release/packages/cran/lfe/R/condfstat.R'
Evaluating '/home/runner/work/renjin-release/renjin-release/packages/cran/lfe/R/demeanlist.R'
Evaluating '/home/runner/work/renjin-release/renjin-release/packages/cran/lfe/R/efactory.R'
Evaluating '/home/runner/work/renjin-release/renjin-release/packages/cran/lfe/R/felm.R'
Evaluating '/home/runner/work/renjin-release/renjin-release/packages/cran/lfe/R/felm.old.R'
Evaluating '/home/runner/work/renjin-release/renjin-release/packages/cran/lfe/R/fixedse.R'
Evaluating '/home/runner/work/renjin-release/renjin-release/packages/cran/lfe/R/generics.R'
Evaluating '/home/runner/work/renjin-release/renjin-release/packages/cran/lfe/R/getfe.R'
Evaluating '/home/runner/work/renjin-release/renjin-release/packages/cran/lfe/R/is.estimable.R'
Evaluating '/home/runner/work/renjin-release/renjin-release/packages/cran/lfe/R/kaczmarz.R'
Evaluating '/home/runner/work/renjin-release/renjin-release/packages/cran/lfe/R/lfe-package.R'
Evaluating '/home/runner/work/renjin-release/renjin-release/packages/cran/lfe/R/nlexpect.R'
Evaluating '/home/runner/work/renjin-release/renjin-release/packages/cran/lfe/R/oldfelm.R'
Evaluating '/home/runner/work/renjin-release/renjin-release/packages/cran/lfe/R/startup.R'
ERROR: Invalid argument: invalid NULL argument to unary function. Expected:
	is.na(integer)
	is.na(double)
	is.na(Symbol)
	is.na(pairlist)
	is.na(character)
	is.na(Complex)
	is.na(byte)
	is.na(list)
  at compareVersion()
Exception in thread "main" java.lang.RuntimeException: Error evaluating package source: startup.R
	at org.renjin.packaging.NamespaceBuilder.evaluateSources(NamespaceBuilder.java:173)
	at org.renjin.packaging.NamespaceBuilder.compile(NamespaceBuilder.java:83)
	at org.renjin.packaging.PackageBuilder.compileNamespace(PackageBuilder.java:184)
	at org.renjin.packaging.GnurPackageBuilder.compile(GnurPackageBuilder.java:110)
	at org.renjin.packaging.GnurPackageBuilder.main(GnurPackageBuilder.java:144)
Caused by: org.renjin.eval.EvalException: Invalid argument: invalid NULL argument to unary function. Expected:
	is.na(integer)
	is.na(double)
	is.na(Symbol)
	is.na(pairlist)
	is.na(character)
	is.na(Complex)
	is.na(byte)
	is.na(list)
	at org.renjin.primitives.R$primitive$is$na.applyPromised(R$primitive$is$na.java:51)
	at org.renjin.sexp.BuiltinFunction.apply(BuiltinFunction.java:100)
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80)
	at org.renjin.eval.Context.evaluate(Context.java:283)
	at org.renjin.primitives.special.IfFunction.apply(IfFunction.java:35)
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:39)
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80)
	at org.renjin.sexp.Closure.applyPromised(Closure.java:200)
	at org.renjin.sexp.Closure.apply(Closure.java:133)
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80)
	at org.renjin.sexp.Promise.doEval(Promise.java:87)
	at org.renjin.sexp.Promise.force(Promise.java:81)
	at org.renjin.primitives.R$primitive$$greater.applyPromised(R$primitive$$greater.java:38)
	at org.renjin.sexp.BuiltinFunction.apply(BuiltinFunction.java:100)
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80)
	at org.renjin.eval.Context.evaluate(Context.java:283)
	at org.renjin.primitives.special.OrFunction.apply(OrFunction.java:49)
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80)
	at org.renjin.eval.Context.evaluate(Context.java:283)
	at org.renjin.primitives.special.IfFunction.apply(IfFunction.java:35)
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80)
	at org.renjin.sexp.ExpressionVector.eval(ExpressionVector.java:85)
	at org.renjin.eval.Context.evaluate(Context.java:283)
	at org.renjin.packaging.NamespaceBuilder.evaluateSources(NamespaceBuilder.java:168)
	... 4 more
```

**Comment by akbertram** [comment]
The offending code is at https://github.com/cran/lfe/blob/2.8-3/R/startup.R#L55
```
RV <- R.Version()
rv <- paste(RV$major,RV$minor, sep='.')
mv <- sessionInfo()$otherPkgs$Matrix$Version
if(compareVersion('3.2-0',rv) > 0 || compareVersion('1.2-0',mv) > 0) {
```
