### ISSUE TITLE
Renjin build fails on AttributeTest

### ISSUE THREAD

**Issue by perNyfelt** [bedatadriven/renjin-release#9]
A fresh checkout of renjin-release fails on the AttributeTest:

> Task :core:test

org.renjin.sexp.AttributeTest > setEmptyDimNamesViaAttr FAILED
    org.renjin.eval.EvalException at AttributeTest.java:295
        Caused by: java.lang.IllegalStateException at AttributeTest.java:295

1348 tests completed, 1 failed, 79 skipped

> Task :core:test FAILED

FAILURE: Build failed with an exception.

Stacktrace details:
org.renjin.eval.EvalException: dimNames should be null or a list with size 2, found: NULL
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:89)
	at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:65)
	at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:42)
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80)
	at org.renjin.sexp.ExpressionVector.eval(ExpressionVector.java:85)
	at org.renjin.eval.Context.evaluate(Context.java:283)
	at org.renjin.eval.Context.evaluate(Context.java:209)
	at org.renjin.EvalTestCase.evaluate(EvalTestCase.java:91)
	at org.renjin.EvalTestCase.eval(EvalTestCase.java:62)
	at org.renjin.sexp.AttributeTest.setEmptyDimNamesViaAttr(AttributeTest.java:295)
....
Caused by: java.lang.IllegalStateException: dimNames should be null or a list with size 2, found: NULL
	at org.renjin.sexp.AttributeMap$Builder.build(AttributeMap.java:793)
	at org.renjin.sexp.AttributeMap$Builder.validateAndBuildForVectorOfLength(AttributeMap.java:840)
	at org.renjin.sexp.AbstractSEXP.setAttributes(AbstractSEXP.java:222)
	at org.renjin.sexp.AbstractSEXP.setAttribute(AbstractSEXP.java:212)
	at org.renjin.sexp.AbstractSEXP.setAttribute(AbstractSEXP.java:207)
	at org.renjin.primitives.Attributes.setAttribute(Attributes.java:323)
	at org.renjin.primitives.R$primitive$attr$assign.doApply(R$primitive$attr$assign.java:67)
	at org.renjin.primitives.R$primitive$attr$assign.applyPromised(R$primitive$attr$assign.java:32)
	at org.renjin.sexp.BuiltinFunction.apply(BuiltinFunction.java:100)
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80)
	... 55 more

**Comment by perNyfelt** [comment]
Changing line 295 of AttributeTest to `eval("attr(x, 'dimnames') <- NULL");` fixes the test but I am not sure this is the right solution.

**Comment by perNyfelt** [comment]
Fixed in PR https://github.com/bedatadriven/renjin/pull/516

**Comment by akbertram** [comment]
I've fixed the regression here: https://github.com/bedatadriven/renjin/commit/8eaefd56019e1fec37a5b0c01f563ce341c04fd6, I will merge the PR above but restore the test case, which remains valid.
